setProposition({
        vehicle: {
          gettingMode: "HAVE_ALREADY_VEHICLE",
          release: "2014-01-01T00:00:00",
          hasVehiculeInsuranceSinceGetting: true,
          fundingMode: "CASH",
          getting: "2020-01-22T14:41:02.390111+01:00",
          sraCode: "KA20020",
          garageMode: "PUBLIC_AREA",
          hasProtectionSystem: false,
          hasTrackingSystem: false,
          postalCode: "59110",
          city: "La Madeleine",
          price: 15000,
          kmTraveled: 2000,
          use: "PRIVATE",
        },
        drivers: {
          driverGroupType: "MYSELF",
          grayCardOwnerType: "SUBSCRIBER",
          hasChildrenOccasionalDrivers: false,
          exclusiveCoupleDriving: false,
          drivers: [
            {
              roleOrder: "MAIN",
              sex: "MALE",
              birthDate: "2000-01-12T00:00:00",
              familySituation: "CIVIL_PARTNERSHIP",
              profession: "EMPLOYEE",
              drivingLicenceObtainedDate: "2020-01-21T14:41:02.395863+01:00",
              accompaniedDriving: true,
              previousInsurance: {
                bonusMalus: 100,
                bonusSenorityYears: 0,
                insuranceSeniority:
                  "YES_WITHOUT_INTERRUPTION_ON_LAST_36_MONTHS_AND_MORE",
                interruptionInsuranceBegin: "2021-01-21T00:00:00+01:00",
                interruptionInsuranceEnd: "2021-01-21T00:00:00+01:00",
                insuranceMonths: 36,
                lastInsuranceName: "AXA",
                hasInsuranceTerminate: false,
                terminateReason: "UNKNOWN",
                terminateBy: null,
              },
            },
          ],
        },
        desiredEffect: "2021-03-14T00:00:00+01:00",
        codeRBS: "SRYBVEW/+33665006574",
      });